// Shared shape for the bundled DT canonical iris-material table
// (src/upgrade/reference/eye-materials.ts, generated by scripts/extract-eye-materials.ts).
// Ported reads: EndwalkerUpgrade.cs · UpdateEyeMask · 2044-2059. Minimum surface: the table's
// KEY is the FileExists oracle (a miss == absent in-game, a faithful skip, :2049); the value
// carries the g_SamplerDiffuse destination path the deferred pixel half will write to (:2058-2059).
// See docs/superpowers/specs/2026-07-16-eye-mask-partial-design.md §3.

/** One existing base-game iris material. Absence from the table == absent in-game (FileExists false). */
export interface EyeMaterialEntry {
  /**
   * g_SamplerDiffuse texture path (EndwalkerUpgrade.cs:2058-2059, `mtrlTex.TexturePath`).
   * Recorded RAW — UpdateEyeMask uses the material's stored TexturePath directly, NOT the
   * `--`-prefixed Dx11 path the hair extractor derives via dx11Path(). Read by the pixel half
   * (`convertEyeMaskToDiffuse`, `src/upgrade/eye-mask.ts`); undefined if the material binds no
   * g_SamplerDiffuse sampler (in which case C#'s :2059 would NRE at pixel time — deferred).
   */
  diffusePath?: string;
}

/** Keyed by iris material game path `mt_c{race}f{face}_iri_a.mtrl` (EndwalkerUpgrade.cs:2044). */
export type EyeMaterialTable = ReadonlyMap<string, EyeMaterialEntry>;
