// Shared shape for the bundled DT canonical hair/tail/ear/accessory material table
// (src/upgrade/reference/hair-materials.ts, generated by scripts/extract-hair-materials.ts).
// Ported reads: EndwalkerUpgrade.cs · UpdateUnclaimedHairTextures/UpdateUnclaimedHairAccessory · 1436-1516 / 1621-1713.
// Minimum surface: only the fields the transform reads. See
// docs/superpowers/specs/2026-07-16-unclaimed-hair-partials-design.md §3.

/** One existing DT canonical material. Absence from the table == absent in-game (FileExists false). */
export interface HairMaterialEntry {
  /** Raw shader-pack name, e.g. "hair.shpk" (ShaderHelpers.cs:558-559). Gates the shader check. */
  shaderPackRaw: string;
  /** g_SamplerNormal Dx11 path (XivMtrl.cs:667-680), if the material binds that sampler. */
  normalDx11Path?: string;
  /** g_SamplerMask Dx11 path, if bound. */
  maskDx11Path?: string;
  /** g_SamplerDiffuse Dx11 path, if bound (accessory only). */
  diffuseDx11Path?: string;
  /** EMaterialFlags1.HideBackfaces (0x01) set on the canonical material (XivMtrl.cs:43). */
  hideBackfaces: boolean;
  /**
   * Base64 of the canonical tail material's raw bytes — present ONLY for tail entries whose
   * canonical material lacks HideBackfaces (the only ones the tail rewrite touches,
   * EndwalkerUpgrade.cs:1504-1516). Absent for every other entry (minimum surface).
   */
  tailRewriteMtrlBase64?: string;
}

/** Keyed by canonical material game path (the `matPath` string.Format target). */
export type HairMaterialTable = ReadonlyMap<string, HairMaterialEntry>;
