// Runtime port of EndwalkerUpgrade.cs:923-936's base-material index-path steal. Data:
// src/upgrade/reference/index-table.ts (generated by scripts/extract-index-table.ts). CRC32
// duplicated from file-exists.ts by the same codebase convention (per-table copy) —
// itself HashGenerator.ComputeCRC (HashGenerator.cs:154-205).
import { base64ToBytes } from "../../util/base64";
import { reconstructIndexPath } from "./index-path-reconstruct";
import { INDEX_EXCEPTIONS, INDEX_PACKED } from "./index-table";

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

/** CRC32 of the lowercased path bytes (init -1, no final XOR), matching HashGenerator.ComputeCRC. */
export function computeHash(path: string): number {
  let crc = 0xffffffff;
  const s = path.toLowerCase();
  for (let i = 0; i < s.length; i++) {
    crc = CRC_TABLE[(crc ^ s.charCodeAt(i)) & 0xff]! ^ (crc >>> 8);
  }
  return crc >>> 0;
}

// TABLE is Map<"folderHash:fileHash", { version: number; keepLetter: boolean }> decoded from
// INDEX_PACKED's 10-byte records (folderHash u32 LE, fileHash u32 LE, then u16 ->
// version = u16 & 0x7fff, keepLetter = (u16 & 0x8000) !== 0).
const TABLE = (() => {
  const bin = base64ToBytes(INDEX_PACKED);
  const dv = new DataView(bin.buffer, bin.byteOffset, bin.byteLength);
  const map = new Map<string, { version: number; keepLetter: boolean }>();
  for (let p = 0; p + 10 <= bin.byteLength; p += 10) {
    const folderHash = dv.getUint32(p, true);
    const fileHash = dv.getUint32(p + 4, true);
    const flags = dv.getUint16(p + 8, true);
    map.set(`${folderHash}:${fileHash}`, {
      version: flags & 0x7fff,
      keepLetter: (flags & 0x8000) !== 0,
    });
  }
  return map;
})();

/** The base material's stolen index (_id.tex) path, or `undefined` if `materialPath` is not a
 *  base-game material carrying an index sampler (EndwalkerUpgrade.cs:923-936). Checks the
 *  INDEX_EXCEPTIONS literal map first, then the packed (version, keepLetter) table reconstructed
 *  via reconstructIndexPath. */
export function resolveStolenIndexPath(
  materialPath: string,
): string | undefined {
  // Fold case first. This resolver is only ever reached from material.ts under
  // `fileExists(mtrl.mtrlPath)`, and `fileExists`'s `_InvalidRegex` gate (file-exists.ts) rejects
  // any uppercase character outright — so a mixed-case `materialPath` can no longer actually reach
  // here; the caller has already made that case unreachable. Kept anyway, purely defensively and at
  // no cost: a no-op for the (only reachable) already-lowercase case, and it keeps this function
  // correct in isolation — case-insensitive against the lowercase INDEX_EXCEPTIONS keys and
  // reconstructed output — should a future caller ever reach it without that guarantee.
  const path = materialPath.toLowerCase();
  const exception = INDEX_EXCEPTIONS[path];
  if (exception !== undefined) return exception;
  const slash = path.lastIndexOf("/");
  if (slash < 0) return undefined;
  const key = `${computeHash(path.slice(0, slash))}:${computeHash(path.slice(slash + 1))}`;
  const rec = TABLE.get(key);
  if (rec === undefined) return undefined;
  return reconstructIndexPath(path, rec.version, rec.keepLetter) ?? undefined;
}
