// Runtime port of EndwalkerUpgrade.cs:923-936's base-material index-path steal. Data:
// src/upgrade/reference/index-table.ts (generated by scripts/extract-index-table.ts). CRC32
// duplicated from hair-texture-exists.ts by the same codebase convention (per-table copy) —
// itself HashGenerator.ComputeCRC (HashGenerator.cs:154-205).
import { base64ToBytes } from "../../util/base64";
import { reconstructIndexPath } from "./index-path-reconstruct";
import { ID_TEX_PACKED, INDEX_EXCEPTIONS, INDEX_PACKED } from "./index-table";

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

/** CRC32 of the lowercased path bytes (init -1, no final XOR), matching HashGenerator.ComputeCRC. */
export function computeHash(path: string): number {
  let crc = 0xffffffff;
  const s = path.toLowerCase();
  for (let i = 0; i < s.length; i++) {
    crc = CRC_TABLE[(crc ^ s.charCodeAt(i)) & 0xff]! ^ (crc >>> 8);
  }
  return crc >>> 0;
}

// TABLE is Map<"folderHash:fileHash", { version: number; keepLetter: boolean }> decoded from
// INDEX_PACKED's 10-byte records (folderHash u32 LE, fileHash u32 LE, then u16 ->
// version = u16 & 0x7fff, keepLetter = (u16 & 0x8000) !== 0).
const TABLE = (() => {
  const bin = base64ToBytes(INDEX_PACKED);
  const dv = new DataView(bin.buffer, bin.byteOffset, bin.byteLength);
  const map = new Map<string, { version: number; keepLetter: boolean }>();
  for (let p = 0; p + 10 <= bin.byteLength; p += 10) {
    const folderHash = dv.getUint32(p, true);
    const fileHash = dv.getUint32(p + 4, true);
    const flags = dv.getUint16(p + 8, true);
    map.set(`${folderHash}:${fileHash}`, {
      version: flags & 0x7fff,
      keepLetter: (flags & 0x8000) !== 0,
    });
  }
  return map;
})();

const ID_TEX_ENTRIES = (() => {
  const bin = base64ToBytes(ID_TEX_PACKED);
  const dv = new DataView(bin.buffer, bin.byteOffset, bin.byteLength);
  const set = new Set<string>();
  for (let p = 0; p + 8 <= bin.byteLength; p += 8) {
    set.add(`${dv.getUint32(p, true)}:${dv.getUint32(p + 4, true)}`);
  }
  return set;
})();

/** The base material's stolen index (_id.tex) path, or `undefined` if `materialPath` is not a
 *  base-game material carrying an index sampler (EndwalkerUpgrade.cs:923-936). Checks the
 *  INDEX_EXCEPTIONS literal map first, then the packed (version, keepLetter) table reconstructed
 *  via reconstructIndexPath. */
export function resolveStolenIndexPath(
  materialPath: string,
): string | undefined {
  // Fold case first: the C# resolution (FileExists / GetXivMtrl) is case-insensitive and `computeHash`
  // already lowercases, but a TTMP2 keys on the raw `FullPath` (no lowercasing), so a mixed-case
  // gamePath could otherwise miss the case-sensitive INDEX_EXCEPTIONS map (its keys, and the
  // reconstructed output, are lowercase — base-game paths are lowercase). A no-op for the common
  // already-lowercase case; keeps every resolution path uniformly case-insensitive.
  const path = materialPath.toLowerCase();
  const exception = INDEX_EXCEPTIONS[path];
  if (exception !== undefined) return exception;
  const slash = path.lastIndexOf("/");
  if (slash < 0) return undefined;
  const key = `${computeHash(path.slice(0, slash))}:${computeHash(path.slice(slash + 1))}`;
  const rec = TABLE.get(key);
  if (rec === undefined) return undefined;
  return reconstructIndexPath(path, rec.version, rec.keepLetter) ?? undefined;
}

/** True iff `path` (folder + "/" + file) is in the bundled base-game `_id.tex` set (gate B:
 *  `!FileExists(idPath)` in EndwalkerUpgrade.cs). Same membership idiom as hairTextureExists. */
export function idTexExists(path: string): boolean {
  const slash = path.lastIndexOf("/");
  if (slash < 0) return false;
  const key = `${computeHash(path.slice(0, slash))}:${computeHash(path.slice(slash + 1))}`;
  return ID_TEX_ENTRIES.has(key);
}
